export USER_DIR_CONFIG="/home/diego/.zsh"

source $USER_DIR_CONFIG/colors.zsh
source $USER_DIR_CONFIG/setopt.zsh
source $USER_DIR_CONFIG/exports.zsh
source $USER_DIR_CONFIG/completion.zsh
source $USER_DIR_CONFIG/aliases.zsh
source $USER_DIR_CONFIG/functions.zsh
source $USER_DIR_CONFIG/history.zsh
source $USER_DIR_CONFIG/git.zsh






# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dpoggi"





# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"



# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
unset GREP_OPTIONS

if [ -f $USER_DIR_CONFIG/zsh_nocorrect ]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < $USER_DIR_CONFIG/zsh_nocorrect
fi